export async function GET() {
  const tickets = [
    {
      id: 't-1001',
      title: 'Cannot connect to VPN',
      description: 'User reports intermittent VPN connectivity errors.',
      priority: 'High',
      status: 'Open',
      assignee: 'Unassigned',
      updatedAt: '2025-10-31T14:05:00Z',
    },
    {
      id: 't-1002',
      title: 'Email attachments failing to upload',
      description: 'Outlook web blocks uploads over 10MB.',
      priority: 'Medium',
      status: 'In Progress',
      assignee: 'Priya Patel',
      updatedAt: '2025-11-01T09:12:00Z',
    },
    {
      id: 't-1003',
      title: 'Laptop battery drains quickly',
      description: 'Battery at 20% after one hour of normal use.',
      priority: 'Low',
      status: 'On Hold',
      assignee: 'Unassigned',
      updatedAt: '2025-10-29T16:30:00Z',
    },
    {
      id: 't-1004',
      title: 'Printer queue stuck on Floor 3',
      description: 'Jobs hang in queue until service restart.',
      priority: 'High',
      status: 'Open',
      assignee: 'Marco Ruiz',
      updatedAt: '2025-10-28T13:47:00Z',
    },
    {
      id: 't-1005',
      title: 'Single sign-on not working for CRM',
      description: 'SSO redirects to error page after login.',
      priority: 'Critical',
      status: 'Open',
      assignee: 'On-Call',
      updatedAt: '2025-11-02T03:15:00Z',
    },
    {
      id: 't-1006',
      title: 'Wifi dead spots in conference rooms',
      description: 'Drops during Zoom calls; rooms A/B affected.',
      priority: 'Medium',
      status: 'In Progress',
      assignee: 'Sara Kim',
      updatedAt: '2025-11-03T10:05:00Z',
    },
    {
      id: 't-1007',
      title: 'New hire account provisioning',
      description: 'Create accounts for 5 interns starting Monday.',
      priority: 'High',
      status: 'Open',
      assignee: 'Unassigned',
      updatedAt: '2025-11-03T12:20:00Z',
    },
    {
      id: 't-1008',
      title: 'MacOS update causing kernel panics',
      description: 'Post-update reboots randomly on M1 devices.',
      priority: 'Critical',
      status: 'In Progress',
      assignee: 'Incident Team',
      updatedAt: '2025-11-04T08:41:00Z',
    },
    {
      id: 't-1009',
      title: 'Access request to shared drive',
      description: 'Marketing team needs read access to /brand.',
      priority: 'Low',
      status: 'Resolved',
      assignee: 'Priya Patel',
      updatedAt: '2025-10-27T09:05:00Z',
    },
    {
      id: 't-1010',
      title: 'Phone extension not receiving calls',
      description: 'VoIP phone rings once then drops.',
      priority: 'Medium',
      status: 'Open',
      assignee: 'Telecom',
      updatedAt: '2025-11-04T14:25:00Z',
    },
    {
      id: 't-1011',
      title: 'SharePoint permissions misconfigured',
      description: 'External users can see internal documents.',
      priority: 'Critical',
      status: 'Open',
      assignee: 'Security',
      updatedAt: '2025-11-05T11:00:00Z',
    },
    {
      id: 't-1012',
      title: 'Slack notifications delayed',
      description: 'Messages arrive in bursts; desktop app.',
      priority: 'Low',
      status: 'On Hold',
      assignee: 'Unassigned',
      updatedAt: '2025-10-30T18:02:00Z',
    },
    {
      id: 't-1013',
      title: 'Broken HDMI port in Room 204',
      description: 'Projector shows “No Signal” on HDMI 1.',
      priority: 'Medium',
      status: 'Open',
      assignee: 'Facilities',
      updatedAt: '2025-11-01T07:55:00Z',
    },
    {
      id: 't-1014',
      title: 'Password reset loop on HR portal',
      description: 'Reset link always says token expired.',
      priority: 'High',
      status: 'In Progress',
      assignee: 'Marco Ruiz',
      updatedAt: '2025-11-03T21:18:00Z',
    },
    {
      id: 't-1015',
      title: 'Teams screen share flickers',
      description: 'Only on dual-monitor setups with Intel GPUs.',
      priority: 'Medium',
      status: 'Open',
      assignee: 'Unassigned',
      updatedAt: '2025-11-05T15:44:00Z',
    },
  ];
  return Response.json(tickets);
}